# Generated by Django 5.1.2 on 2025-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_order_shipping_cost_order_shipping_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
