# Generated by Django 5.1.1 on 2025-03-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_mainpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
